version: "3"

services:
  rt5:
    image: tomboone/rt5-apache-amd64:latest
    container_name: rt5
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm
      - ./ssl:/etc/ssl
      - ./sites-available:/etc/apache2/sites-available
    command: apachectl -D FOREGROUND

  mariadb:
    image: tomboone/rt5-mariadb-amd64:latest
    container_name: mariadb
    restart: always
    ports:
      - "8306:3306"
    volumes:
      - ./rt5.sql:/docker-entrypoint-initdb.d/rt5.sql
      - rt5-mariadb-data:/var/lib/mysql

volumes:
    rt5-mariadb-data: