version: "3"

services:
  rt5:
    build: .
    container_name: rt5
    working_dir: /opt/rt5
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm
      - ./sites-available:/etc/apache2/sites-available:ro
      - ./ssl/mycert.crt:/etc/ssl/certs/mycert.crt:ro
      - ./ssl/mycert.key:/etc/ssl/private/mycert.key:ro
    depends_on:
      - mariadb
    ports:
      - "80:80"
      - "443:443"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "8306:3306"
    environment:
        MARIADB_ROOT_PASSWORD: rt5
        MYSQL_DATABASE: rt5
        MYSQL_USER: rt5
        MYSQL_PASSWORD: rt5
    volumes:
      - ./rt5.sql:/docker-entrypoint-initdb.d/rt5.sql
      - rt5-mariadb-data:/var/lib/mysql

volumes:
    rt5-mariadb-data: