version: "3"

services:
  rt5:
    build: .
    container_name: rt5
    working_dir: /opt/rt5
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm
      - ./sites-available:/etc/apache2/sites-available:ro
      - ./html:/var/www/html:ro
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rt5.rule=Host(`rt5.wrlc.localhost`)"
      - "traefik.http.routers.rt5.entrypoints=websecure"
      - "traefik.http.routers.rt5.tls=true"
    networks:
      - proxy

  rt5_db:
    image: mariadb:latest
    container_name: rt5_db
    environment:
        MARIADB_ROOT_PASSWORD: rt5
        MYSQL_DATABASE: rt5
        MYSQL_USER: rt_user
        MYSQL_PASSWORD: rt_pass
    volumes:
      - ./rt5.sql:/docker-entrypoint-initdb.d/rt5.sql
      - rt5-mariadb-data:/var/lib/mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rt5_db.rule=Host(`db.rt5.wrlc.localhost`)"
      - "traefik.tcp.services.rt5_db.loadbalancer.server.port=3306"
      - "traefik.http.routers.rt5_db.entrypoints=mysql"
    networks:
        - proxy

volumes:
    rt5-mariadb-data:

networks:
  proxy:
    external: true
